TeenHope/urls.py
from django.conf.urls import patterns, include, url
from django.conf.urls.static import static

from TeenHope import settings

# Uncomment the next two lines to enable the admin:
from django.contrib import admin

admin.autodiscover()

urlpatterns = patterns('',
                       # Examples:
                       # url(r'^$', 'TeenHope.views.home', name='home'),
                       # url(r'^TeenHope/', include('TeenHope.foo.urls')),

                       # Uncomment the admin/doc line below to enable admin documentation:
                       url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

                       # Uncomment the next line to enable the admin:
                       url(r'^admin/', include(admin.site.urls)),

                       url(r'^forum/', include('forum.urls', namespace="forum")),
                       url(r'^accounts/', include('accounts.urls', namespace="accounts")),
                       url(r'^pages/', include('pages.urls', namespace="pages")),
                       url(r'^$', "forum.views.home", name="home"),
                       url(r'^xadmin/', include('xadmin.urls', namespace="xadmin")),
                       url(r'^network/', include('network.urls', namespace="network")),

) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

forum/urls.py
from django.conf.urls import patterns, url
from forum import views

urlpatterns = patterns('',
                       url(r'^category$', views.all_category_index, name='all_category_index'),
                       url(r'^category/all$', views.all_topic_index, name='all_topic_index'),
                       url(r'^category/(?P<label>\w+)/$', views.specific_category_index, name='specific_category_index'),
                       url(r'^topic/(?P<topic_id>\d+)/new_post/$', views.new_post, name="new_post"),
                       url(r'^topic/(?P<topic_id>\d+)/$', views.topic_detail, name='topic_detail'),
                       url(r'^post/(?P<post_id>\d+)/post_reply/$', views.post_reply, name="post_reply"),
)

xadmin/urls.py
from django.conf.urls import patterns, url
from xadmin import views


urlpatterns = patterns('',
                       url(r'^dashboard/$', views.dashboard, name='dashboard'),
                       url(r'^inbox/$', views.inbox, name='inbox'),
                       url(r'^show_msg_in_inbox/(?P<msg_id>\d+)$', views.show_msg_in_inbox, name="show_msg_in_inbox"),
                       # url(r'^send_msg/$', views.send_msg, name="send_msg"),
                       # url(r'^add_connections/$', views.add_connections, name="add_connections"),
                       url(r'^manage_connections/$', views.manage_connections, name="manage_connections"),
                       url(r'^new_topic/$', views.new_topic, name="new_topic"),
                       url(r'^new_article/$', views.new_article, name="new_article"),
                       url(r'^recent_traces/$', views.recent_traces, name="recent_traces"),
                       url(r'^update_profile/$', views.update_profile, name='update_profile'),
                       url(r'^on_checkbox$',views.on_checkbox,name="on_checkbox"),
                       url(r'^ckbox_select_all/(?P<page>\d+)$',views.ckbox_select_all,name="ckbox_select_all"),
                       url(r'^ckbox_unselect_all/(?P<page>\d+)$',views.ckbox_unselect_all,name="ckbox_unselect_all"),
                       url(r'^ckbox_remove$',views.ckbox_remove,name="ckbox_remove"),
                       url(r'^ckbox_mark$',views.ckbox_mark,name="ckbox_mark"),
                       url(r'^ckbox_unmark$',views.ckbox_unmark,name="ckbox_unmark"),
                       url(r'^inbox_search$',views.inbox_search,name="inbox_search"),
                       url(r'^inbox_mark_one$',views.inbox_mark_one,name="inbox_mark_one"),
                       url(r'^inbox_unmark_one$',views.inbox_unmark_one,name="inbox_unmark_one"),
                       url(r'^chpsw_sendmail$',views.chpsw_sendmail,name="chpsw_sendmail"),
                       url(r'^chpsw_ckhash$',views.chpsw_ckhash,name="chpsw_ckhash"),
                       url(r'^chpsw_doupdate$',views.chpsw_doupdate,name="chpsw_doupdate"),
                       url(r'^mancon_remove$',views.mancon_remove,name="mancon_remove"),
                       url(r'^mancon_newgroup$',views.mancon_newgroup,name="mancon_newgroup"),
                       url(r'^mancon_edit_groupname/(?P<group_id>\d+)$',views.mancon_edit_groupname,name="mancon_edit_groupname"),
                       url(r'^mancon_move_selected/(?P<group_id>\d+)$',views.mancon_move_selected,name="mancon_move_selected"),
                       url(r'^mancon_move_single/(?P<group_id>\d+)$',views.mancon_move_single,name="mancon_move_single"),
                       url(r'^mancon_clear_group/(?P<group_id>\d+)$',views.mancon_clear_group,name="mancon_clear_group"),
                       url(r'^mancon_remove_group/(?P<group_id>\d+)$',views.mancon_remove_group,name="mancon_remove_group"),
                       url(r'^activate_ckhash$',views.activate_ckhash,name="activate_ckhash"),
)

xadmin/models.py
from django.db import models

# Create your models here.

pages/forms.py
from django import forms
from TeenHope import settings
from pages.models import Tag


class NewArticleForm(forms.Form):
    tags = forms.CharField(widget=forms.HiddenInput(), required=False)
    title = forms.CharField()
    abstract = forms.CharField(widget=forms.Textarea())
    content = forms.CharField(widget=forms.Textarea())

    def __init__(self, user, *args, **kwargs):
        super(NewArticleForm, self).__init__(*args, **kwargs)
        self.fields['tags'].queryset = Tag.objects.filter(author=user)

    def clean_title(self):
        title = self.cleaned_data['title']
        if title is None:
            raise forms.ValidationError("Title cannot be empty.")
        elif len(title) > settings.ARTICLE_TITLE_LENGTH_LIMIT:
            raise forms.ValidationError("Title length must be no longer"
                                        "than %d characters." % settings.ARTICLE_TITLE_LENGTH_LIMIT)
        return title

    def clean_abstract(self):
        abstract = self.cleaned_data['abstract']

        if abstract is None:
            raise forms.ValidationError("Abstract cannot be empty.")
        elif len(abstract) > settings.ABSTRACT_LENGTH_LIMIT:
            raise forms.ValidationError("Article abstract must be no longer"
                                        "than %d characters." % settings.ABSTRACT_LENGTH_LIMIT)
        return abstract

    def clean_content(self):
        content = self.cleaned_data['content']

        if content is None:
            raise forms.ValidationError("Content cannot be empty.")
        elif len(content) > settings.ARTICLE_LENGTH_LIMIT:
            raise forms.ValidationError("Article content must be no longer"
                                        "than %d characters." % settings.ARTICLE_LENGTH_LIMIT)
        return content


class NewCommentForm(forms.Form):
    content = forms.CharField(widget=forms.Textarea())

    def clean(self):
        cleaned_data = super(NewCommentForm, self).clean()

        content = cleaned_data.get('content')

        if content is None:
            raise forms.ValidationError("Content cannot be empty.")
        elif len(content) > settings.COMMENT_LENGTH_LIMIT:
            raise forms.ValidationError("Comment content must be no longer than"
                                        "%d characters." % settings.COMMENT_LENGTH_LIMIT)

        return cleaned_data

xadmin/forms.py
from django import forms
from django.core.exceptions import ValidationError
from TeenHope import settings
from forum.models import *


class NewTopicForm(forms.Form):
    category = forms.ModelChoiceField(
        queryset=Category.objects.all(),
        initial=Category.objects.get(id=1)
    )
    title = forms.CharField()
    content = forms.CharField(widget=forms.Textarea)

    def clean(self):
        cleaned_data = super(NewTopicForm, self).clean()

        title = cleaned_data.get('title')
        content = cleaned_data.get('content')

        if title is None:
            raise forms.ValidationError("Title cannot be empty.")
        elif len(title) > settings.TOPIC_TITLE_LENGTH_LIMIT:
            raise forms.ValidationError("Title length must be no longer "
                                        "than %d characters." % settings.TOPIC_TITLE_LENGTH_LIMIT)
        if content is None:
            raise forms.ValidationError("Content cannot be empty.")
        elif len(content) > settings.POST_LENGTH_LIMIT:
            raise forms.ValidationError("Post content must be no longer"
                                        "than %d characters." % settings.POST_LENGTH_LIMIT)

        return cleaned_data


class NewMessageForm(forms.Form):
    subject = forms.CharField()
    content = forms.CharField(widget=forms.Textarea())
    receivers = forms.CharField(widget=forms.HiddenInput())

    def clean(self):
        cleaned_data = super(NewMessageForm, self).clean()

        subject = cleaned_data.get('subject')
        content = cleaned_data.get('content')
        receivers = cleaned_data.get('receivers')

        if receivers is None or receivers == "":
            raise forms.ValidationError("Choose at least one receiver.")
        if subject is None:
            raise forms.ValidationError("Subject cannot be empty.")
        elif len(subject) > settings.MESSAGE_SUBJECT_LENGTH_LIMIT:
            raise forms.ValidationError("Subject length must be no longer "
                                        "than %d characters." % settings.MESSAGE_SUBJECT_LENGTH_LIMIT)
        if content is None:
            raise forms.ValidationError("Content cannot be empty.")
        elif len(content) > settings.MESSAGE_LENGTH_LIMIT:
            raise forms.ValidationError("Message content must be no longer"
                                        "than %d characters." % settings.MESSAGE_LENGTH_LIMIT)

        return cleaned_data


class AddConnectionsForm(forms.Form):
    friends = forms.CharField(widget=forms.HiddenInput())

    def clean(self):
        cleaned_data = super(AddConnectionsForm, self).clean()
        friends = cleaned_data.get('friends')

        if friends is None or friends == "":
            raise forms.ValidationError("At least add one person.")

        return cleaned_data


from accounts.models import validate_email, validate_nickname, validate_website


class ProfileForm(forms.Form):
    first_name = forms.CharField(required=False)
    last_name = forms.CharField(required=False)
    nickname = forms.CharField(validators=[validate_nickname])
    email = forms.CharField(validators=[validate_email])
    thumbnail = forms.ImageField(required=False)

    website = forms.CharField(required=False)
    renren = forms.CharField(required=False)
    qq = forms.CharField(required=False)
    phone = forms.CharField(required=False)

    biography = forms.CharField(required=False, widget=forms.Textarea)
    motto = forms.CharField(required=False, widget=forms.Textarea)

    def clean_thumbnail(self):
        image = self.cleaned_data['thumbnail']
        if image:
            if image.size > 4 * 1024 * 1024:
                raise ValidationError("Image file too large (> 4mb).")


    def clean_website(self):
        website = self.cleaned_data['website']
        if website:
            validate_website(website)
        return website


from accounts.models import validate_password


class ChangePasswordForm(forms.Form):
    old_password = forms.CharField()
    new_password = forms.CharField(validators=[validate_password])
    re_password = forms.CharField(validators=[validate_password])

    def __init__(self, user=None, *args, **kwargs):
        super(ChangePasswordForm, self).__init__(*args, **kwargs)
        self.__user = user

    def clean_old_password(self):
        old_password = self.cleaned_data['old_password']
        if not self.__user.check_password(old_password):
            raise ValidationError("Incorrect password.")
        return old_password

    def clean(self):
        cleaned_data = super(ChangePasswordForm, self).clean()

        new_password = cleaned_data.get('new_password')
        re_password = cleaned_data.get('re_password')

        if new_password != re_password:
            raise forms.ValidationError('Inconsistent passwords.')

        return cleaned_data

class InboxSearchForm(forms.Form):
    is_marked = forms.BooleanField(required = False)
    is_unread = forms.BooleanField(required = False)
    content = forms.CharField(max_length = settings.MESSAGE_SUBJECT_LENGTH_LIMIT,required=False)

    def clean(self):
        cleaned_data = super(InboxSearchForm,self).clean()

        is_marked = cleaned_data.get('is_marked')
        if not is_marked:
            cleaned_data['is_marked'] = False

        is_unread = cleaned_data.get('is_unread')
        if not is_unread:
            cleaned_data['is_unread']  = False

        content = cleaned_data.get('content')
        if not content:
            cleaned_data['content'] = ''

        return cleaned_data


from accounts.models import validate_password
class ChangePasswordForm(forms.Form):
    username = forms.CharField()
    hash_key = forms.CharField()
    password = forms.CharField(validators=[validate_password], widget=forms.PasswordInput)
    re_password = forms.CharField(validators=[validate_password], widget=forms.PasswordInput)

    def clean(self):
        cleaned_data = super(ChangePasswordForm, self).clean()

        pswd1 = cleaned_data.get('password')
        pswd2 = cleaned_data.get('re_password')
        if pswd1 != pswd2:
            raise ValidationError("Please enter the same passwords twice.")

        return cleaned_data

xadmin/templates/xadmin/change_password.html
{% extends "xadmin/xadmin_base.html" %}
{% load staticfiles %}
{% load widget_tweaks %}
{% block title %}
    Change password
{% endblock %}
{% block xadmin_head %}
    <link rel="stylesheet" type="text/css" href="{% static "xadmin/change_password.css" %}">
{% endblock %}
{% block xadmin_content %}
    <h2 class="xadmin-headline">
        <i class="icon-lock"></i>
        <span>Change Password</span>
    </h2>
    <form method="POST" action="{% url 'xadmin:chpsw_doupdate' %}">
        {% csrf_token %}
        {{ form.errors }}
        <div class="row-fluid">
            <div class="span6 offset 3">
                <label for="id_password">Enter your new password here</label>
                {{ form.password|add_class:"input-block-level" }}
                <label for="id_re_password">Enter the above password again</label>
                {{ form.re_password|add_class:"input-block-level" }}
                <input type="text" name="username" style="display:none" value="{{ usr }}"/>
                <input type="text" name="hash_key" style="display:none" value="{{ key }}"/>
                <input class="btn btn-large btn-warning" type="submit" value="Change Now">
            </div>
        </div>
    </form>
{% endblock %}

xadmin/templates/xadmin/inbox.html
{% extends "xadmin/xadmin_base.html" %}
{% load staticfiles %}
{% block title %}
    Inbox
{% endblock %}
{% block xadmin_head %}
    <link rel="stylesheet" type="text/css" href="{% static "xadmin/inbox.css" %}">

    <script>
        $(function () {
            $('td.subject-column').click(function () {
                var url_mask = "{% url 'xadmin:show_msg_in_inbox' msg_id=12345 %}"
                        .replace(/12345/, $(this).parent().attr('msg_id'));
                document.location = url_mask;
            })

            $('td.checkbox-column').click(function () {
                msg_id = $(this).parent().attr('msg_id');
                $.get("{% url 'xadmin:on_checkbox' %}", {msg_id: msg_id});

                ck = $(this).find(":checkbox");
                ck.attr("checked", !ck.attr("checked"));
            })

            function select_all_flag(flag) {
                ck_list = $("#message-table").find(":checkbox");
                for (var i = 0; i < ck_list.length; i++) {
                    ck_list[i].checked = flag;
                }
                ck_list.trigger('change');
            }

            $('#select-all-btn').click(function () {
                select_all_flag(true);
                url = $(this).attr("href");
                $.get(url);
            });

            $('#unselect-all-btn').click(function () {
                select_all_flag(false);
                url = $(this).attr("href");
                $.get(url);
            });

            function mark_flag(flag) {
                $('#message-table').find(":checkbox").each(function () {
                    cur = $(this);
                    if (cur.attr("checked")) {
                        td = cur.parent().parent().find("td.important-column");
                        if (flag) {
                            td.html("<i class='icon-star'></i>");
                        } else {
                            td.html("<i class='icon-star-empty'></i>");
                        }
                    }
                });
            }

            $('#mark-btn').click(function () {
                mark_flag(true);
                url = $(this).attr('href');
                $.get(url);
            });


            $('#unmark-btn').click(function () {
                mark_flag(false);
                url = $(this).attr('href');
                $.get(url);
            });

            $('td.important-column').click(function () {
                cur = $(this);
                state = cur.find("i").attr("class");
                msg_id = cur.parent().attr("msg_id");
                url = "";

                if (state == "icon-star") {
                    state = "icon-star-empty";
                    url = "{% url 'xadmin:inbox_unmark_one' %}";
                } else {
                    state = "icon-star";
                    url = "{% url 'xadmin:inbox_mark_one' %}";
                }

                $.get(url, {
                    msg_id: msg_id,
                }, function () {
                    cur.find("i").attr("class", state);
                });

                return false;
            });
        })
    </script>
{% endblock %}
{% block xadmin_content %}
    <div>
        <h2 class="xadmin-headline">
            <i class="icon-inbox"></i>
            <span>Inbox</span>
        </h2>

        <div class="container">
            <div class="navbar">
                <div class="btn-toolbar pull-left">
                    <div class="btn-group">
                        <button class="btn" href="{% url 'xadmin:ckbox_select_all' msgs.number %}" id="select-all-btn">
                            Select All
                        </button>
                        <button class="btn" href="{% url 'xadmin:ckbox_unselect_all' msgs.number %}"
                                id="unselect-all-btn">Unselect All
                        </button>
                    </div>
                    <div class="btn-group">
                        <a class="btn" href="{% url 'xadmin:ckbox_remove' %}">Remove</a>
                        <button class="btn" href="{% url 'xadmin:ckbox_mark' %}" id="mark-btn">Mark</button>
                        <button class="btn" href="{% url 'xadmin:ckbox_unmark' %}" id="unmark-btn">Unmark</button>
                    </div>
                    <div class="btn-group form-wrapper">
                        <form class="form-search" method="GET" action="{% url 'xadmin:inbox_search' %}">
                            <input type="checkbox" name="is_marked"><label class="checkbox">marked?</label>
                            <input type="checkbox" name="is_unread" checked="checked"><label class="checkbox">unread?</label>
                            <input type="text" class="input-medium search-query input-block-level" name="content">
                            <button type="submit" class="btn">Search</button>
                        </form>
                    </div>
                </div>

                <div class="pagination pull-right">
                    <ul>
                        {% if msgs.has_previous %}
                            <li><a href="?page={{ msgs.previous_page_number }}&{{ GET_data.urlencode }}">«</a></li>
                        {% else %}
                            <li class="disabled"><a>«</a></li>
                        {% endif %}

                        </li>

                        <li>
                            <a href="#">
                                Page {{ msgs.number }} of {{ msgs.paginator.num_pages }}
                            </a>
                        </li>

                        {% if msgs.has_next %}
                            <li><a href="?page={{ msgs.next_page_number }}&{{ GET_data.urlencode }}">»</a></li>
                        {% else %}
                            <li class="disabled"><a>»</a></li>
                        {% endif %}
                    </ul>
                </div>
            </div>
            <table class="table table-hover" id="message-table">
                <thead>
                <tr>
                    <th>&nbsp;</th>
                    <th>Flag</th>
                    <th>Sent by</th>
                    <th>Subject</th>
                    <th>Date</th>
                </tr>
                </thead>
                <tbody>
                {% for msg in msgs %}
                    <tr class="inbox-row
                        {% if msg.unread %}row-bold{% endif %}"
                        msg_id="{{ msg.id }}">
                        <td class="checkbox-column">
                            <input type="checkbox"
                                    {% if msg.checked %}
                                   checked="checked"
                                    {% endif %}/>
                        </td>
                        <td class="important-column">
                            {% if msg.important %}
                                <i class="icon-star"></i>
                            {% else %}
                                <i class="icon-star-empty"></i>
                            {% endif %}
                        </td>
                        <td>{{ msg.sender.get_profile.nickname }}</td>
                        <td class="subject-column">{{ msg.subject }}</td>
                        <td>{{ msg.date_sent|date:"M d, Y" }}</td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>

        </div>
    </div>{% endblock %}

xadmin/templates/xadmin/new_article.html
{% extends "xadmin/xadmin_base.html" %}
{% load staticfiles %}
{% load widget_tweaks %}
{% block xadmin_head %}
    <link rel="stylesheet" type="text/css" href="{% static "pages/new_article.css" %}">

    <script>
        $(function () {
            CKEDITOR.replace('id_abstract', {
                customConfig: '{% static 'ckeditor4.2/config.js' %}'
            });
            CKEDITOR.replace('id_content', {
                customConfig: '{% static 'ckeditor4.2/config_full.js' %}'
            });
            $("#id_tags").tagit({
                singleField: true,
                singleFieldNode: $("#id_tags")
            });

        })
    </script>
{% endblock %}
{% block title %}Create A New Article{% endblock %}
{% block xadmin_content %}
    <h2 class="xadmin-headline">
        <i class="icon-plus-sign"></i>
        <span>Create A New Article</span>
    </h2>
    <div class="span8">
        <form method="POST" action=""> {% csrf_token %}
            {{ form.non_field_errors }}
            <div class="row-fluid">
                <label class="label-headline" for="id_category">Add Tags</label>

                {{ form.tags }}
                <label class="label-headline" for="id_title">Title</label>
                {{ form.title.errors }}
                {{ form.title|add_class:"input-block-level" }}

                <label class="label-headline" for="id_abstract">Abstract</label>
                {{ form.abstract.errors }}
                {{ form.abstract }}

                <label class="label-headline" for="id_content">Content</label>
                {{ form.content.errors }}
                {{ form.content }}
                <input id="publish_btn" class="btn btn-warning btn-large"
                       type="submit" value="Publish">
            </div>
        </form>
    </div>
{% endblock %}

xadmin/templates/xadmin/update_profile.html
{% extends "xadmin/xadmin_base.html" %}
{% load staticfiles %}
{% load widget_tweaks %}

{% block title %}Update your profile{% endblock %}
{% block xadmin_head %}
    <link rel="stylesheet" type="text/css" href="{% static "xadmin/update_profile.css" %}">
    <script>
        $(function () {
            $('#upload_btn').click(function () {
                $('#id_thumbnail').click();
            })
            $('#id_thumbnail').change(function () {
                $('#thumbnail_path').text($(this).val());
            })
            CKEDITOR.inline('id_biography', {
                customConfig: '{% static 'ckeditor4.2/config_intermediate.js' %}'
            });
            CKEDITOR.inline('id_motto', {
                customConfig: '{% static 'ckeditor4.2/config.js' %}'
            });
        })
    </script>
{% endblock %}
{% block xadmin_content %}
    <h2 class="xadmin-headline">
        <i class="icon-edit"></i>
        <span>Update Profile</span>
    </h2>

    <form method="POST" class="form-horizontal" action="" enctype="multipart/form-data"> {% csrf_token %}
        {{ form.errors }}
        <div class="row-fluid">

            <div class="span7">
                <fieldset>
                    <legend>Name</legend>
                    <div class="control-group">
                        <label class="control-label" for="id_first_name">first name</label>

                        <div class="controls">
                            {{ form.first_name|add_class:"input-block-level" }}
                        </div>
                    </div>
                    <div class="control-group">
                        <label class="control-label" for="id_last_name">last name</label>

                        <div class="controls">
                            {{ form.last_name|add_class:"input-block-level" }}
                        </div>
                    </div>
                    <div class="control-group">
                        <label class="control-label" for="id_nickname">nickname</label>

                        <div class="controls">
                            {{ form.nickname|add_class:"input-block-level" }}
                        </div>
                    </div>

                </fieldset>
                <fieldset>
                    <legend>Contact</legend>
                    <div class="control-group">
                        <label class="control-label" for="id_website">website</label>

                        <div class="controls">
                            {{ form.website|add_class:"input-block-level" }}
                        </div>
                    </div>
                    <div class="control-group">
                        <label class="control-label" for="id_renren">renren</label>

                        <div class="controls">
                            {{ form.renren|add_class:"input-block-level" }}
                        </div>
                    </div>
                    <div class="control-group">
                        <label class="control-label" for="id_qq">qq</label>

                        <div class="controls">
                            {{ form.qq|add_class:"input-block-level" }}
                        </div>
                    </div>
                    <div class="control-group">
                        <label class="control-label" for="id_phone">phone</label>

                        <div class="controls">
                            {{ form.phone|add_class:"input-block-level" }}
                        </div>
                    </div>
                    <div class="control-group">
                        <label class="control-label" for="id_email">email</label>

                        <div class="controls">
                            {{ form.email|add_class:"input-block-level" }}
                        </div>
                    </div>
                </fieldset>

                <fieldset>
                    <legend>About</legend>
                    <div class="meta">
                        Tip: Click to edit inline.
                    </div>
                    <div class="control-group">
                        <label class="control-label" for="id_biography">biography</label>

                        <div class="controls">
                            {{ form.biography|add_class:"input-block-level" }}
                        </div>
                    </div>
                    <div class="control-group">
                        <label class="control-label" for="id_motto">motto</label>

                        <div class="controls">
                            {{ form.motto|add_class:"input-block-level" }}
                        </div>
                    </div>


                </fieldset>
            </div>
            <div class="span5 thumbnail-box">
                <div class="span6">
                    <img id="upload_btn" class="portrait" src="{{ request.user.get_profile.thumbnail.url }}">

                    <div>
                        File:
                        <span id="thumbnail_path">Not selected</span>

                        <input class="hide" type="file" id="id_thumbnail" name="thumbnail">
                    </div>
                </div>
                <div class="span6 thumbnail-hint">Click the thumbnail to select file for uploading</div>


            </div>
        </div>

        <input class="btn btn-primary btn-large" type="submit" value="update">
        </div>
    </form>


{% endblock %}

xadmin/templates/xadmin/xadmin_base.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block head %}
    <link rel="stylesheet" type="text/css" href="{% static "xadmin/xadmin_base.css" %}">
    <script>
        $(function() {
            $("#change-password-link").click(function() {
                return window.confirm("Do you want to change your password?(This will send a email to your email-inbox)");
            })
        });
    </script>
    {% block xadmin_head %}
    {% endblock %}
{% endblock %}
{% block content %}
    <div class="row-fluid">
        <div class="span2">
            <div class="well sidebar-nav">
                <ul class="nav nav-list">
                    <li><a href="{% url 'xadmin:dashboard' %}">Dashboard</a></li>


                    <li class="nav-header">Connections</li>
                    <li><a href="{% url 'xadmin:inbox' %}">Inbox</a></li>

                    <li><a href="{% url 'xadmin:manage_connections' %}">Manage connections</a></li>


                    <li class="nav-header">My activities</li>
                    <li><a href="{% url 'xadmin:new_topic' %}">New topic</a></li>
                    <li><a href="{% url 'xadmin:new_article' %}">New article</a></li>
                    <li><a href="{% url 'xadmin:recent_traces' %}">Recent traces</a></li>


                    <li class="nav-header">Account</li>
                    <li><a href="{% url 'xadmin:update_profile' %}">Update personal info</a></li>
                    <li><a href="{% url 'xadmin:chpsw_sendmail' %}" id="change-password-link">Change Password</a></li>
                </ul>
            </div>
            <!--/.well -->
        </div>
        <!--/span-->

        <div class="span10">
            <div class="row-fluid main-content">
                {% block xadmin_content %}
                {% endblock %}
            </div>
        </div>
    </div>

{% endblock %}