TeenHope/urls.py
from django.conf.urls import patterns, include, url
from django.conf.urls.static import static

from TeenHope import settings

# Uncomment the next two lines to enable the admin:
from django.contrib import admin

admin.autodiscover()

urlpatterns = patterns('',
                       # Examples:
                       # url(r'^$', 'TeenHope.views.home', name='home'),
                       # url(r'^TeenHope/', include('TeenHope.foo.urls')),

                       # Uncomment the admin/doc line below to enable admin documentation:
                       url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

                       # Uncomment the next line to enable the admin:
                       url(r'^admin/', include(admin.site.urls)),

                       url(r'^forum/', include('forum.urls', namespace="forum")),
                       url(r'^accounts/', include('accounts.urls', namespace="accounts")),
                       url(r'^pages/', include('pages.urls', namespace="pages")),
                       url(r'^$', "forum.views.home", name="home"),
                       url(r'^xadmin/', include('xadmin.urls', namespace="xadmin")),
                       url(r'^network/', include('network.urls', namespace="network")),

) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/urls.py
from django.conf.urls import patterns, url
from accounts import views

urlpatterns = patterns('',
                       url(r'^login/$', views.login, name='login'),
                       url(r'^logout/$', views.logout, name='logout'),
                       url(r'^register/$', views.register, name='register'),
                       url(r'^view_profile/(?P<user_id>\d+)/$', views.view_profile, name='view_profile'),
                       url(r'^forget_password$', views.forget_password, name='forget_password'),
)

forum/urls.py
from django.conf.urls import patterns, url
from forum import views

urlpatterns = patterns('',
                       url(r'^category$', views.all_category_index, name='all_category_index'),
                       url(r'^category/all$', views.all_topic_index, name='all_topic_index'),
                       url(r'^category/(?P<label>\w+)/$', views.specific_category_index, name='specific_category_index'),
                       url(r'^topic/(?P<topic_id>\d+)/new_post/$', views.new_post, name="new_post"),
                       url(r'^topic/(?P<topic_id>\d+)/$', views.topic_detail, name='topic_detail'),
                       url(r'^post/(?P<post_id>\d+)/post_reply/$', views.post_reply, name="post_reply"),
)

network/urls.py
from django.conf.urls import patterns, url
from network import views


urlpatterns = patterns('',
                       url(r'^accept_invitation/(?P<user_id>\d+)/$', views.accept_invitation, name="accept_invitation"),
                       url(r'^remove_friend/$', views.remove_friend, name="remove_friend"),
                       url(r'^send_invitation/$', views.send_invitation, name="send_invitation"),
                       url(r'^add_follow/$', views.add_follow, name="add_follow"),
                       url(r'^send_message/$', views.send_message_single, name="send_message"),
                       url(r'^send_message_selected$',views.send_message_selected,name="send_message_selected"),
                       url(r'^subscribe_topic/$', views.subscribe_topic, name="subscribe_topic"),
                       url(r'^unsubscribe_topic/$', views.unsubscribe_topic, name="unsubscribe_topic"),
                       url(r'^subscribe_article/$', views.subscribe_article, name="subscribe_article"),
                       url(r'^unsubscribe_article/$', views.unsubscribe_article, name="unsubscribe_article"),
)

accounts/models.py
import re
from django.core.exceptions import ValidationError
from django.db import models
from django.contrib.auth.models import User
from TeenHope import settings
from django.core.urlresolvers import reverse

class Profile(models.Model):
    user = models.OneToOneField(User)       # handle of default User object
    first_name = models.CharField(max_length=settings.PROFILE_NAME_LENGTH_LIMIT)
    last_name = models.CharField(max_length=settings.PROFILE_NAME_LENGTH_LIMIT)
    nickname = models.CharField(max_length=settings.PROFILE_NAME_LENGTH_LIMIT)
    thumbnail = models.ImageField(upload_to="thumbnail",
                                  default=settings.DEFAULT_USER_THUMBNAIL)

    website = models.CharField(max_length=settings.WEBSITE_LENGTH_LIMIT)
    renren = models.CharField(max_length=settings.RENREN_LENGTH_LIMIT)
    qq = models.CharField(max_length=settings.QQ_LENGTH_LIMIT)
    phone = models.CharField(max_length=settings.PHONE_LENGTH_LIMIT)

    biography = models.CharField(max_length=settings.BIOGRAPHY_LENGTH_LIMIT)
    motto = models.CharField(max_length=settings.MOTTO_LENGTH_LIMIT)

    def __unicode__(self):
        return self.nickname + "'s Profile"

    def get_unread_message_cnt(self):
        from network.models import Message

        return Message.objects.filter(receiver=self.user, unread=True).count()

    def get_absolute_url(self):
        return reverse('accounts:view_profile', kwargs={'user_id': self.id})




from django.db.models.signals import post_save


def auto_create_profile(sender, **kwargs):
    user = kwargs["instance"]
    if kwargs["created"]:
        Profile.objects.create(user=user, nickname=user.username)


post_save.connect(auto_create_profile, sender=User)


def validate_username(username):
    if not username:
        raise ValidationError("Username cannot be none.")
    if not re.compile(settings.USERNAME_PATTERN).match(username):
        raise ValidationError(settings.USERNAME_HINT)


def validate_password(password):
    if not password:
        raise ValidationError("Password cannot be none.")
    if not re.compile(settings.PASSWORD_PATTERN).match(password):
        raise ValidationError(settings.PASSWORD_HINT)


def validate_email(email):
    if not email:
        raise ValidationError("Email is required.")
    if not re.compile(settings.EMAIL_PATTERN).match(email):
        raise ValidationError("Invalid email format.")


def validate_nickname(nickname):
    if not nickname:
        raise ValidationError("Nickname is required.")
    if not re.compile(settings.NICKNAME_PATTERN).match(nickname):
        raise ValidationError("Invalid nickname.")


def validate_website(website):
    if not re.compile(settings.WEBSITE_PATTERN).match(website):
        raise ValidationError('Invalid website.')

pages/models.py
from django.db import models
from django.contrib.auth.models import User
from django.core.urlresolvers import reverse

from TeenHope import settings


class Tag(models.Model):
    author = models.ForeignKey(User)
    title = models.CharField(max_length=settings.TAG_LENGTH_LIMIT)

    def __unicode__(self):
        return self.title

    def count(self):
        return self.article_set.count()


class Article(models.Model):
    author = models.ForeignKey(User)
    date_published = models.DateTimeField(auto_now_add=True)
    title = models.CharField(max_length=settings.ARTICLE_TITLE_LENGTH_LIMIT)
    content = models.TextField(max_length=settings.ARTICLE_LENGTH_LIMIT)
    tags = models.ManyToManyField(Tag)
    abstract = models.CharField(max_length=settings.ABSTRACT_LENGTH_LIMIT)

    def __unicode__(self):
        return "Article: " + self.title

    def get_absolute_url(self):
        return reverse('pages:detail', kwargs={'article_id': self.id})

    def trace_msg(self):
        return "Create article#%d <strong>%s</strong>" % (self.id, self.title)

    def get_subscribe_subject(self):
        return "%s has created a new article" % self.author.get_profile().nickname

    def get_subscribe_content(self):
        return "<a href=%s>Click here to view</a>" % self.get_absolute_url()


class Comment(models.Model):
    author = models.ForeignKey(User)
    article = models.ForeignKey(Article)
    date_published = models.DateTimeField(auto_now_add=True)
    content = models.CharField(max_length=settings.COMMENT_LENGTH_LIMIT)

    def __unicode__(self):
        return "Comment #%d for Article %s" % (self.id, self.article.title)

    def get_absolute_url(self):
        return reverse('pages:detail', kwargs={'article_id': self.article.id})

    def trace_msg(self):
        return "Post a comment(#%d) on article <strong>%s</strong>" % (self.id, self.article.title)

    def get_subscribe_subject(self):
        return "%s has created a new comment" % self.author.get_profile().nickname

    def get_subscribe_content(self):
        return "<a href=%s>Click here to view</a>" % self.get_absolute_url()

accounts/forms.py
import re

from django import forms
from django.contrib import auth
from django.contrib.auth.models import User
from django.core.exceptions import ValidationError

from TeenHope import settings
from accounts.models import validate_username



class LoginForm(forms.Form):
    username = forms.CharField() # validators=[username_validator]
    password = forms.CharField(widget=forms.PasswordInput) # validators=[password_validator]

    def clean(self):
        cleaned_data = super(LoginForm, self).clean()
        username = cleaned_data.get('username')
        password = cleaned_data.get('password')
        user = auth.authenticate(username=username, password=password)
        if user is None:
            raise forms.ValidationError("Unmatched username and password.")
        elif not user.is_active:
            raise forms.ValidationError("The account has been disabled.")
        return cleaned_data

from accounts.models import validate_email, validate_password, validate_username


class RegistrationForm(forms.Form):
    username = forms.CharField(validators=[validate_username])
    password = forms.CharField(validators=[validate_password], widget=forms.PasswordInput)
    re_password = forms.CharField(validators=[validate_password], widget=forms.PasswordInput)
    email = forms.CharField(validators=[validate_email])

    def clean_username(self):
        tmp = self.cleaned_data['username']
        if User.objects.filter(username=tmp).count():
            raise forms.ValidationError("Username being occupied.")
        return tmp

    def clean_email(self):
        tmp = self.cleaned_data['email']
        if User.objects.filter(email=tmp).count():
            raise forms.ValidationError("Email has been used.")
        return tmp

    def clean(self):
        cleaned_data = super(RegistrationForm, self).clean()
        username = cleaned_data.get('username')

        pswd1 = cleaned_data.get('password')

        pswd2 = cleaned_data.get('re_password')
        if pswd2:
            if pswd1 != pswd2:
                msg = "You must enter the same password twice."
                self._errors["re_password"] = self.error_class([msg])

                del cleaned_data["re_password"]

        return cleaned_data




class ForgetPasswordForm(forms.Form):
    username = forms.CharField(validators=[validate_username])
    email = forms.CharField(validators=[validate_email])

accounts/views.py
from django.core.urlresolvers import reverse
from django.contrib import auth
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.contrib.auth.decorators import login_required
from django.contrib import messages

from forms import LoginForm


def login(request):
    if request.method == 'POST':
        form = LoginForm(request.POST)
        if form.is_valid():
            username = form.cleaned_data['username']
            password = form.cleaned_data['password']
            user = auth.authenticate(username=username, password=password)
            if user.is_active:
                auth.login(request, user)
                if 'next' in request.GET:
                    return HttpResponseRedirect(request.GET['next'])
                else:
                    return HttpResponseRedirect(reverse('home'))
            else:
                return activate(request)
    else:
        form = LoginForm()

    return render(request, 'accounts/login.html', {
        'login_form': form,
    })

@login_required()
def logout(request):
    auth.logout(request)
    if 'next' in request.GET:
        return HttpResponseRedirect(request.GET['next'])
    return HttpResponseRedirect(reverse('home'))


from forms import RegistrationForm
from django.contrib.auth.models import User


def register(request):
    if request.method == 'POST':
        form = RegistrationForm(request.POST)
        if form.is_valid():
            user = User.objects.create_user(
                form.cleaned_data['username'], form.cleaned_data['email'], form.cleaned_data['password']
            )
            user.is_active = False
            user.save()

            return activate(request, user)

            #auth.login(request, user)
            #if 'next' in request.GET:
            #    return HttpResponseRedirect(request.GET['next'])
            #return HttpResponseRedirect(reverse('home'))
    else:
        form = RegistrationForm()

    return render(request, 'accounts/register.html', {
        'register_form': form,
    })

def activate(request, user):
    from xadmin.views import activate_send_email
    activate_send_email(request, user)
    return render(request, 'accounts/activate.html')

from django.shortcuts import get_object_or_404
from forum.models import *
from pages.models import *
from network.models import *

def view_profile(request, user_id):
    user = get_object_or_404(User, id=user_id)
    profile = user.get_profile()
    stat = {
        'topic_cnt': Topic.objects.filter(author=user).count(),
        'post_cnt': Post.objects.filter(author=user).count(),
        'reply_cnt': Reply.objects.filter(author=user).count(),
        'article_cnt': Article.objects.filter(author=user).count(),
        'comment_cnt': Comment.objects.filter(author=user).count(),
        'tag_cnt': Tag.objects.filter(author=user).count(),
        'friend_cnt': user.relationlist.friends.count(),
        'following_cnt': user.relationlist.followings.count(),
        'follower_cnt': RelationList.objects.filter(followings=user).count(),
    }
    has_login = request.user.is_authenticated()
    is_friend = False
    if request.user.is_authenticated():
        if request.user.relationlist.friends.filter(id=user.id).count() > 0\
            or request.user.id == user.id:
            is_friend = True

    has_followed = False
    if request.user.is_authenticated():
        if request.user.relationlist.followings.filter(id=user.id).count() > 0\
        or request.user.id == user.id:
            has_followed = True

    topic_list = Topic.objects.filter(author=user).order_by('-date_published')[:5]
    post_list = Post.objects.filter(author=user).order_by('-date_published')[:5]
    article_list = Article.objects.filter(author=user).order_by('-date_published')[:5]
    comment_list = Comment.objects.filter(author=user).order_by('-date_published')[:5]
    tag_list = Tag.objects.filter(author=user)[:10]


    return render(request, 'accounts/view_profile.html', {
        'this_user': user,
        'profile': profile,
        'stat': stat,
        'has_login': has_login,
        'is_friend': is_friend,
        'has_followed': has_followed,
        'topic_list': topic_list,
        'post_list': post_list,
        'article_list': article_list,
        'comment_list': comment_list,
        'tag_list': tag_list,
    })


from accounts.forms import ForgetPasswordForm
def forget_password(request):
    if request.method == "POST":
        fpf = ForgetPasswordForm(request.POST)
        if fpf.is_valid():
            user = User.objects.get(username = fpf.cleaned_data['username'])
            if user and user.email == fpf.cleaned_data['email']:
                from xadmin.views import _chpsw_sendmail
                return _chpsw_sendmail(request,user,reverse("accounts:forget_password"))
    return render(request, 'accounts/forgot_password.html')

accounts/templates/accounts/accounts.html
{% extends "base.html" %}
{% load staticfiles %}
{% load widget_tweaks %}
{% block title %}Accounts management{% endblock %}
{% block head %}
    <link rel="stylesheet" type="text/css" href="{% static "css/accounts.css" %}">
    <script>
        $(function () {
            var path = window.location.pathname;
            if (path.indexOf('login') >= 0) {
                $('#login_tab').addClass("active");
            }
            if (path.indexOf('register') >= 0) {
                $('#register_tab').addClass("active");
            }
            if (path.indexOf('forget_password') >= 0) {
                $('#forget_password_tab').addClass("active");
            }

        })
    </script>
{% endblock %}
{% block content %}
    <div class="container accounts-panel">
        <div class="span8 offset2">
            <div class="tabbable custom-tabs">
                <ul class="nav nav-tabs">
                    <li id="login_tab" class=""><a href="{% url 'accounts:login' %}">
                        <i class="icon-lock"></i>&nbsp;<span>Login Panel</span></a>
                    </li>
                    <li id="register_tab" class=""><a href="{% url 'accounts:register' %}">
                        <i class="icon-user"></i>&nbsp;<span>Register Panel</span></a>
                    </li>
                    <li id="forget_password_tab" class=""><a href="{% url 'accounts:forget_password' %}">
                        <i class="icon-key"></i>&nbsp;<span>Forget Password</span></a>
                    </li>
                </ul>

                <div class="tab-content">
                    {% block accounts_content %}{% endblock %}
                </div>

            </div>

        </div>
    </div>
{% endblock %}

accounts/templates/accounts/activate.html
{% extends 'accounts/accounts.html' %}
{% load widget_tweaks %}
{% block accounts_content %}
    <div>
        Please check your Mail-Box to activate your account.
    </div>
{% endblock %}

accounts/templates/accounts/forgot_password.html
{% extends 'accounts/accounts.html' %}
{% load widget_tweaks %}
{% block accounts_content %}
    <div class="tab-pane active" id="panel3">
        <div class="row-fluid">
            <div class="span5">
                <h4><i class="icon-unlock"></i>&nbsp;&nbsp;Password Recovery</h4>
                <form action="{% url 'accounts:forget_password' %}" method='POST' id="forget-password-form">
                    {% csrf_token %}
                    <label>Username</label>
                    <input type="text" class="input-block-level" name="username" />
                    <label>Email</label>
                    <input type="text" class="input-block-level" name="email" />
                
                    <br>
                    <br>
                    <a class="btn" onclick="$('#forget-password-form').submit();">Send confirmation mail&nbsp;&nbsp;&nbsp;<i class="icon-chevron-sign-right"></i></a>
                </form>
            </div>
            <div class="span7">
                <h4><i class="icon-question"></i>&nbsp;&nbsp;Help</h4>

                <div class="box">
                    <p>
                        Enter your username and email address used when registering and an
                        email for confirmation will be sent.
                    </p>

                </div>
            </div>
        </div>


    </div>
{% endblock %}

accounts/templates/accounts/login.html
{% extends 'accounts/accounts.html' %}
{% load widget_tweaks %}
{% block accounts_content %}
    <div class="tab-pane active" id="panel1">
        <div class="row-fluid">

            <div class="span5">
                <form id="login_form" method="POST"
                      action="{% url 'accounts:login' %}{% if request.GET.next %}?next={{ request.GET.next }}{% endif %}"> {% csrf_token %}
                    <h4><i class="icon-user"></i>&nbsp;&nbsp; Login Here</h4>
                    {{ login_form.non_field_errors }}
                    <label>Username</label>
                    {{ login_form.username.errors }}
                    {{ login_form.username|add_class:"input-block-level" }}
                    <label>Password<a href="#panel3" class="pull-right" tabindex=-1><i
                            class="icon-question-sign"></i>Forgot
                        Password</a>
                    </label>
                    {{ login_form.password.errors }}
                    {{ login_form.password|add_class:"input-block-level" }}
                    <br>

                    <a onclick="$('#login_form').submit();" class="btn">Sign In&nbsp;&nbsp;&nbsp;<i
                            class="icon-chevron-sign-right"></i></a>
                </form>
            </div>
            <div class="span3">
                <h4><i class="icon-expand-alt"></i>&nbsp;&nbsp;Social</h4>

                <div class="socials clearfix">
                    Comming soon...
                </div>
            </div>
            <div class="span4">
                <h4><i class="icon-question"></i>&nbsp;&nbsp;Registration</h4>

                <div class="box">
                    <p>
                        Quickly sign in to see new updates and make new friends!
                    </p>
                </div>
                <div class="box">
                    Don't Have An Account.<br>
                    Click Here For <a href="{% url 'accounts:register' %}">Free Register</a>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

accounts/templates/accounts/register.html
{% extends 'accounts/accounts.html' %}
{% load widget_tweaks %}
{% block accounts_content %}
    <div class="tab-pane active" id="panel2">
        <div class="row-fluid">
            <div class="span5">
                <form method="POST" id="register_form"
                      action="{% url 'accounts:register' %}{% if request.GET.next %}?next={{ request.GET.next }}{% endif %}"> {% csrf_token %}
                    <h4><i class="icon-user"></i>&nbsp;&nbsp; Register Here</h4>
                    {{ register_form.non_field_errors }}

                    <label>Username</label>
                    {{ register_form.username.errors }}
                    {{ register_form.username|add_class:"input-block-level" }}
                    <label>Password </label>
                    {{ register_form.password.errors }}
                    {{ register_form.password|add_class:"input-block-level" }}
                    <label>Repeat Password</label>
                    {{ register_form.re_password.errors }}
                    {{ register_form.re_password|add_class:"input-block-level" }}
                    <label>Email</label>
                    {{ register_form.email.errors }}
                    {{ register_form.email|add_class:"input-block-level" }}
                    <br>

                    <a onclick="$('#register_form').submit();" class="btn"
                            >Register Now&nbsp;&nbsp;&nbsp;
                        <i class="icon-chevron-sign-right"></i></a>
                </form>
            </div>
            <div class="span3">
                <h4><i class="icon-expand-alt"></i>&nbsp;&nbsp;Social</h4>

                <div class="socials clearfix">
                    Comming soon...
                </div>
            </div>
            <div class="span4">
                <h4><i class="icon-question"></i>&nbsp;&nbsp;Login</h4>

                <div class="box">
                    <p>
                        Sign up now and be part of our Cornucopian family!
                    </p>
                </div>
                <div class="box">
                    Already Have An Account.<br>
                    Click Here For <a href="{% url 'accounts:login' %}">Login</a>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

accounts/templates/accounts/update_profile.html
{% extends "base.html" %}
{% load staticfiles %}
{% block title %}Update your profile{% endblock %}
{% block head %}
    <link rel="stylesheet" type="text/css" href="{% static "accounts/update_profile.css" %}">
{% endblock %}
{% block content %}
    <div class="update-profile-wrapper">
        <div class="header-container">
            <h1>Profile Editing</h1>
        </div>

        <div class="main-profile">
            <div class="portrait-wrapper">
                <img class="portrait" src="{% static 'accounts/default_portrait.jpg' %}">
            </div>
            <form method="POST" action=""> {% csrf_token %}
                <div class="error_msg">
                    {{ form.errors }}
                </div>

                <div class="section" id="name">
                    <h2>Name</h2>

                    <div>
                        <label for="id_first_name">First Name</label>
                        {{ form.first_name }}
                    </div>
                    <div>
                        <label for="id_last_name">Last Name</label>
                        {{ form.last_name }}
                    </div>
                    <div>
                        <label for="id_nickname">Nickname</label>
                        {{ form.nickname }}
                    </div>
                </div>

                <div class="section" id="contact_info">
                    <h2>Contact Info</h2>

                    <div>
                        <label for="id_website">Personal Website</label>
                        {{ form.website }}
                    </div>
                    <div>
                        <label for="id_renren">Renren</label>
                        {{ form.renren }}
                    </div>
                    <div>
                        <label for="id_qq">QQ</label>
                        {{ form.qq }}
                    </div>

                    <div>
                        <label for="id_phone">Phone</label>
                        {{ form.phone }}
                    </div>
                </div>

                <div class="section" id="biography">
                    <h2>About Yourself</h2>

                    <div>
                        <label for="id_biography">Biographical Info</label>
                        {{ form.biography }}
                    </div>
                    <div>
                        <label for="id_motto">Motto</label>
                        {{ form.motto }}
                    </div>
                </div>

                <div class="section" id="account">
                    <h2>Account</h2>

                    <div>
                        <label for="id_email">Email</label>
                        {{ form.email }}
                    </div>
                    <div>
                        <label for="id_password">New Password</label>
                        {{ form.new_password }}
                    </div>
                    <div>
                        <label for="id_re_password">Re-enter New Password</label>
                        {{ form.re_password }}
                    </div>
                </div>

                <input class="button blue-button"
                       type="submit" value="Update Profile"/>

            </form>

        </div>


    </div>
{% endblock %}