TeenHope/urls.py
from django.conf.urls import patterns, include, url
from django.conf.urls.static import static

from TeenHope import settings

# Uncomment the next two lines to enable the admin:
from django.contrib import admin

admin.autodiscover()

urlpatterns = patterns('',
                       # Examples:
                       # url(r'^$', 'TeenHope.views.home', name='home'),
                       # url(r'^TeenHope/', include('TeenHope.foo.urls')),

                       # Uncomment the admin/doc line below to enable admin documentation:
                       url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

                       # Uncomment the next line to enable the admin:
                       url(r'^admin/', include(admin.site.urls)),

                       url(r'^forum/', include('forum.urls', namespace="forum")),
                       url(r'^accounts/', include('accounts.urls', namespace="accounts")),
                       url(r'^pages/', include('pages.urls', namespace="pages")),
                       url(r'^$', "forum.views.home", name="home"),
                       url(r'^xadmin/', include('xadmin.urls', namespace="xadmin")),
                       url(r'^network/', include('network.urls', namespace="network")),

) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

forum/urls.py
from django.conf.urls import patterns, url
from forum import views

urlpatterns = patterns('',
                       url(r'^category$', views.all_category_index, name='all_category_index'),
                       url(r'^category/all$', views.all_topic_index, name='all_topic_index'),
                       url(r'^category/(?P<label>\w+)/$', views.specific_category_index, name='specific_category_index'),
                       url(r'^topic/(?P<topic_id>\d+)/new_post/$', views.new_post, name="new_post"),
                       url(r'^topic/(?P<topic_id>\d+)/$', views.topic_detail, name='topic_detail'),
                       url(r'^post/(?P<post_id>\d+)/post_reply/$', views.post_reply, name="post_reply"),
)

network/urls.py
from django.conf.urls import patterns, url
from network import views


urlpatterns = patterns('',
                       url(r'^accept_invitation/(?P<user_id>\d+)/$', views.accept_invitation, name="accept_invitation"),
                       url(r'^remove_friend/$', views.remove_friend, name="remove_friend"),
                       url(r'^send_invitation/$', views.send_invitation, name="send_invitation"),
                       url(r'^add_follow/$', views.add_follow, name="add_follow"),
                       url(r'^send_message/$', views.send_message_single, name="send_message"),
                       url(r'^send_message_selected$',views.send_message_selected,name="send_message_selected"),
                       url(r'^subscribe_topic/$', views.subscribe_topic, name="subscribe_topic"),
                       url(r'^unsubscribe_topic/$', views.unsubscribe_topic, name="unsubscribe_topic"),
                       url(r'^subscribe_article/$', views.subscribe_article, name="subscribe_article"),
                       url(r'^unsubscribe_article/$', views.unsubscribe_article, name="unsubscribe_article"),
)

pages/urls.py
from django.conf.urls import patterns, url
from pages import views

urlpatterns = patterns('',
                       url(r'^$', views.index, name="index"),
                       url(r'^(?P<article_id>\d+)$', views.detail, name="detail"),
                       url(r'^new_comment/(?P<article_id>\d+)/$', views.new_comment, name="new_comment"),
                       )

forum/models.py
from django.core.urlresolvers import reverse
from django.db import models
from django.contrib.auth.models import User
from TeenHope import settings
from django.db.models.signals import post_save
import datetime

class Category(models.Model):
    title = models.CharField(max_length=settings.CATEGORY_TITLE_LENGTH_LIMIT)  # title of the category
    label = models.CharField(max_length=settings.CATEGORY_LABEL_LENGTH_LIMIT)
    description = models.CharField(default="Description goes here...", max_length=settings.CATEGORY_DESCRIPTION_LENGTH_LIMIT)
    topic_cnt = models.IntegerField(default=0)
    post_cnt = models.IntegerField(default=0)
    last_editor_id = models.IntegerField(default=0)
    last_modified_time = models.DateTimeField(auto_now_add=True)

    def __unicode__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('forum:specific_category_index', kwargs={'label': self.label})


class Topic(models.Model):
    category = models.ForeignKey(Category, default=1)     # one topic belongs to only one kind
    title = models.CharField(max_length=settings.TOPIC_TITLE_LENGTH_LIMIT)         # title of the topic
    date_published = models.DateTimeField(auto_now_add=True)
    author = models.ForeignKey(User)
    rank = models.IntegerField(default=0)

    def __unicode__(self):
        return "Topic: " + self.title

    def get_absolute_url(self):
        return reverse('forum:topic_detail', kwargs={'topic_id': self.id})

    def trace_msg(self):
        return "Create topic#%d <strong>%s</strong>" % (self.id, self.title)

    def get_participants(self):
        return [y.author for y in self.post_set.all()]

    def get_subscribe_subject(self):
        return "%s has created a new topic" % self.author.get_profile().nickname

    def get_subscribe_content(self):
        return "<a href=%s>Click here to view</a>" % self.get_absolute_url()

    def get_last_post(self):
        return self.post_set.order_by('-date_published')[0]


class Post(models.Model):
    topic = models.ForeignKey(Topic)    # a post belongs to only one topic
    author = models.ForeignKey(User)    # the writer of the post
    date_published = models.DateTimeField(auto_now_add=True)         # time published
    content = models.TextField(
        max_length=settings.POST_LENGTH_LIMIT)        # content of the post, no limited char number

    def __unicode__(self):
        return "Post #%d for Topic %s" % (self.id, self.topic.title)

    def get_absolute_url(self):
        return reverse('forum:topic_detail', kwargs={'topic_id': self.topic.id})

    def trace_msg(self):
        return "Follow up#%d for topic <strong>%s</strong>" % (self.id, self.topic.title)

    def get_subscribe_subject(self):
        return "%s has created a new post" % self.author.get_profile().nickname

    def get_subscribe_content(self):
        return "<a href=%s>Click here to view</a>" % self.get_absolute_url()


class Reply(models.Model):
    post = models.ForeignKey(Post)      # reply to a single post
    author = models.ForeignKey(User)    # who replies
    date_published = models.DateTimeField(auto_now_add=True) # time published
    content = models.CharField(max_length=settings.REPLY_LENGTH_LIMIT)  # content of the reply

    def __unicode(self):
        return "A reply by " + self.author.name

    def trace_msg(self):
        return "Reply#%d to post#%d of topic <strong>%s</strong>" % (self.id, self.post.id, self.post.topic.title)

    def get_absolute_url(self):
        return self.post.get_absolute_url()

    def get_subscribe_subject(self):
        return "%s has replied your post" % self.author.get_profile().nickname

    def get_subscribe_content(self):
        return "<a href=%s>Click here to view</a>" % self.get_absolute_url()


def listen_to_topic(sender, **kwargs):
    topic = kwargs["instance"]
    if kwargs["created"]:
        cat = topic.category
        cat.topic_cnt += 1
        cat.save()

post_save.connect(listen_to_topic, sender=Topic)

def listen_to_post(sender, **kwargs):
    post = kwargs["instance"]
    if kwargs["created"]:
        topic = post.topic
        cat = topic.category
        cat.post_cnt += 1
        cat.last_editor_id = post.author.id
        cat.last_modified_time = post.date_published
        cat.save()

post_save.connect(listen_to_post, sender=Post)

def listen_to_category(sender, **kwargs):
    cat = kwargs["instance"]
    llx = User.objects.get(id=1)
    if kwargs["created"]:
        topic = Topic.objects.create(category=cat, title="Placeholder for category %s" % cat.title,
                                         author=llx)
        Post.objects.create(topic=topic, author=llx,
                                       content="This topic has no meaning. Simply for placeholding. Please DO NOT reply.")

post_save.connect(listen_to_category, sender=Category)

pages/forms.py
from django import forms
from TeenHope import settings
from pages.models import Tag


class NewArticleForm(forms.Form):
    tags = forms.CharField(widget=forms.HiddenInput(), required=False)
    title = forms.CharField()
    abstract = forms.CharField(widget=forms.Textarea())
    content = forms.CharField(widget=forms.Textarea())

    def __init__(self, user, *args, **kwargs):
        super(NewArticleForm, self).__init__(*args, **kwargs)
        self.fields['tags'].queryset = Tag.objects.filter(author=user)

    def clean_title(self):
        title = self.cleaned_data['title']
        if title is None:
            raise forms.ValidationError("Title cannot be empty.")
        elif len(title) > settings.ARTICLE_TITLE_LENGTH_LIMIT:
            raise forms.ValidationError("Title length must be no longer"
                                        "than %d characters." % settings.ARTICLE_TITLE_LENGTH_LIMIT)
        return title

    def clean_abstract(self):
        abstract = self.cleaned_data['abstract']

        if abstract is None:
            raise forms.ValidationError("Abstract cannot be empty.")
        elif len(abstract) > settings.ABSTRACT_LENGTH_LIMIT:
            raise forms.ValidationError("Article abstract must be no longer"
                                        "than %d characters." % settings.ABSTRACT_LENGTH_LIMIT)
        return abstract

    def clean_content(self):
        content = self.cleaned_data['content']

        if content is None:
            raise forms.ValidationError("Content cannot be empty.")
        elif len(content) > settings.ARTICLE_LENGTH_LIMIT:
            raise forms.ValidationError("Article content must be no longer"
                                        "than %d characters." % settings.ARTICLE_LENGTH_LIMIT)
        return content


class NewCommentForm(forms.Form):
    content = forms.CharField(widget=forms.Textarea())

    def clean(self):
        cleaned_data = super(NewCommentForm, self).clean()

        content = cleaned_data.get('content')

        if content is None:
            raise forms.ValidationError("Content cannot be empty.")
        elif len(content) > settings.COMMENT_LENGTH_LIMIT:
            raise forms.ValidationError("Comment content must be no longer than"
                                        "%d characters." % settings.COMMENT_LENGTH_LIMIT)

        return cleaned_data

pages/templates/pages/detail.html
{% extends "pages/pages_base.html" %}
{% load staticfiles %}
{% load access_to_settings %}

{% block pages_head %}
    <link rel="stylesheet" type="text/css" href="{% static "pages/detail.css" %}">
    <script>
        $(function () {
            CKEDITOR.replace('id_content', {
                customConfig: '{% static 'ckeditor4.2/config_intermediate.js' %}'
            });
            $('#subscribe_btn').click(function () {
                $.ajax({
                    type: "GET",
                    url: '{% url 'network:subscribe_article' %}',
                    data: {
                        'article_id': {{ article.id }}
                    },
                    success: function () {
                        $("#subscribe_btn").hide(1000);
                        $('#unsubscribe_btn').show(1000);
                        return false;
                    }
                })
            })
            $('#unsubscribe_btn').click(function () {
                $.ajax({
                    type: "GET",
                    url: '{% url 'network:unsubscribe_article' %}',
                    data: {
                        'article_id': {{ article.id }}
                    },
                    success: function () {
                        $('#unsubscribe_btn').hide(1000);
                        $('#subscribe_btn').show(1000);
                        return false;
                    }
                })
            })
        })
    </script>
{% endblock %}
{% block pages_content %}
    <div class="row-fluid">
        <div class="span7 offset2 main-wrapper">
            {% if user.is_authenticated %}
                <div class="pull-right">
                <button id="subscribe_btn" class="btn btn-info {% if has_subscribed %}hide{% endif %}">Subscribe
                </button>
                <button id="unsubscribe_btn" class="btn btn-warning {% if has_subscribed %}{% else %}hide{% endif %}">
                    Unsubscribe
                </button>
                </div>
            {% endif %}
            <h2>{{ article.title }}</h2>

            <div class="author">
                <span class="">
                    By &nbsp; &nbsp;
                    <a href="{{ article.author.get_profile.get_absolute_url }}">
                        <img src="{{ article.author.get_profile.thumbnail.url }}">
                        {{ article.author.get_profile.nickname }}</a>

                </span>
            </div>
            <ul class="meta">
                <li>
                    <i class="icon-time"></i>
                    {{ article.date_published|date:"P, M d" }}
                </li>
                <li>
                    <i class="icon-comment"></i>
                    {{ article.comment_set.all.count }} comment{{ article.comment_set.all.count|pluralize }}
                </li>
                <li>
                    <i class="icon-tags"></i>
                    {% if article.tags.all %}
                        <ul class="tag-preview">
                            {% for tag in article.tags.all %}
                                <li>
                                    <a href="{{ tag.get_absolute_url }}">{{ tag.title }}
                                    </a>
                                </li>
                            {% endfor %}
                        </ul>
                    {% else %}
                        <span class="tag">No tag</span>
                    {% endif %}
                </li>
            </ul>
            <div class="content-wrapper">
                {{ article.content|safe }}
            </div>
            <ul id="comment-list">
                {% for comment in article.comment_set.all %}
                    <div class="comment" id="comment_{{ comment.id }}">
                        <div class="comment-meta">
                            <span class="comment-index"># {{ forloop.counter }}</span>

                            <span class="comment-author">
                                <img src="{{ request.user.get_profile.thumbnail.url }}">
                                <a href="{{ comment.author.get_profile.get_absolute_url }}">
                                    {{ comment.author.get_profile.nickname }}
                                </a>
                            </span>

                            <span class="comment-date">
                                {{ comment.date_published|date:"P" }}
                                {{ comment.date_published|date:"M d, Y" }}
                            </span>
                        </div>
                        <div class="comment-content">
                            {{ comment.content|safe }}
                        </div>


                    </div>
                {% endfor %}
            </ul>

            <div class="comment-box">
                <h3>Leave a Comment</h3>

                <form method="post" action="{% url 'pages:new_comment' article_id=article.id %}"> {% csrf_token %}
                    <div class="error_msg">
                        {{ comment_form.non_field_errors }}
                    </div>
                    <div class="textarea-div">
                        {{ comment_form.content }}
                    </div>

                    <input id="comment-submit-btn" class="btn btn-info btn-large" type="submit"
                           value="Submit Comment">
                </form>
            </div>
        </div>
    </div>

{% endblock %}

pages/templates/pages/index.html
{% extends "pages/pages_base.html" %}
{% load staticfiles %}
{% load sum_month_cnt %}
{% block pages_head %}
    <link rel="stylesheet" type="text/css" href="{% static "pages/index.css" %}">
    <script>
        $(function () {
            $('.additional-limit').hide();
            $('#search-toggle-btn').click(function () {
                $('.additional-limit').fadeToggle(700);
            })
            $('.archive-level1').click(function() {
                sublist = $(this).siblings('.row-fluid');
                sublist.slideToggle(700);
            })
            $('.archive-level2').click(function () {
                sublist = $(this).siblings('ul');
                sublist.slideToggle(700);
            })
        })
    </script>
{% endblock %}
{% block pages_content %}
    <div class="row-fluid">

        <div class="span7 offset1 main-wrapper">
            <div class="pagination pull-right">
                <ul>
                    {% if articles.has_previous %}
                        <li><a href="?page={{ articles.previous_page_number }}">«</a></li>
                    {% else %}
                        <li class="disabled"><a>«</a></li>
                    {% endif %}

                    </li>

                    <li>
                        <a href="#">
                            Page {{ articles.number }} of {{ articles.paginator.num_pages }}
                        </a>
                    </li>

                    {% if articles.has_next %}
                        <li><a href="?page={{ articles.next_page_number }}">»</a></li>
                    {% else %}
                        <li class="disabled"><a>»</a></li>
                    {% endif %}
                </ul>
            </div>
            <div style="clear:both"></div>
            <div class="content">
                <ul class="article-list">
                    {% for article in articles %}
                        <li>
                            <h2>
                                <a class="article-title"
                                   href="{% url 'pages:detail' article.id %}">
                                    {{ article.title }}
                                </a>
                            </h2>

                            <ul class="meta">
                                <li>
                                    <i class="icon-edit"></i>
                                    <a href="{{ article.author.get_profile.get_absolute_url }}">
                                        {{ article.author.get_profile.nickname }}</a>
                                </li>
                                <li>
                                    <i class="icon-time"></i>
                                    {{ article.date_published|date:"P, M d" }}
                                </li>
                                <li>
                                    <i class="icon-comment"></i>

                                    <a href="{% url 'pages:detail' article.id %}#comment-list">
                                        {{ article.comment_set.count }}
                                        comment{{ article.comment_set.count|pluralize }}
                                    </a>
                                </li>
                                <li>
                                    <i class="icon-tags"></i>
                                    {% if article.tags.all %}
                                        {% for tag in article.tags.all %}
                                            <span class="tag">
                                                <a href="{{ tag.get_absolute_url }}">{{ tag.title }}</a>
                                            </span>
                                        {% endfor %}
                                    {% else %}
                                        <span class="tag">No tag</span>
                                    {% endif %}
                                </li>
                            </ul>
                            <div class="abstract">
                                {{ article.abstract|safe }}
                            </div>

                            <a class="btn btn-primary read-more" href="{% url 'pages:detail' article.id %}">Read
                                more</a>
                        </li>

                    {% endfor %}
                </ul>
            </div>
        </div>

        <div class="span4">
            <form method="GET" class="input-block-level" action="{% url 'pages:index' %}">
                <div class="input-append" style="width:100%">
                    <input type="text" class="span8" style="height:30px;" name="title"
                           placeholder="Title here"
                           value="{{ GET_data.title }}">

                    <div class="btn-group">
                        <a id="search-toggle-btn" class="btn"><i class="icon-angle-down"></i></a>
                        <input type="submit" class="btn btn-danger" value="Search"></input>
                    </div>
                </div>
                <div class="additional-limit">
                    <div class="control-group">
                        <label class="control-label" for="id_author">Author</label>

                        <div class="controls">
                            <input id="author" type="text" name="author" class="input-block-level"
                                   placeholder="Author"
                                   value="{{ GET_data.author }}">
                        </div>
                    </div>

                    <div class="control-group">
                        <label class="control-label" for="id_abstract">In abstract</label>

                        <div class="controls">
                            <input id="abstract" type="text" name="abstract" class="input-block-level"
                                   placeholder="Abstract here"
                                   value="{{ GET_data.abstract }}">
                        </div>
                    </div>

                    <div class="control-group">
                        <label class="control-label" for="id_tags">Tags</label>

                        <div class="controls">
                            <input id="tags" type="text" name="tags" class="input-block-level"
                                   placeholder="Tags here (spaced by ',')"
                                   value="{{ GET_data.tags }}">
                        </div>
                    </div>
                    <div class="control-group">
                        <label class="control-label" for="id_pub_time_start">Date from</label>

                        <div class="controls">
                            <input id="pub_time_start" type="text" name="pub_time_start" class="input-block-level"
                                   placeholder="e.g. '2012/12/21', inclusively"
                                   value="{{ GET_data.pub_time_start }}">
                        </div>
                    </div>
                    <div class="control-group">
                        <label class="control-label" for="id_pub_time_end">Date to</label>

                        <div class="controls">
                            <input id="pub_time_end" type="text" name="pub_time_end" class="input-block-level"
                                   placeholder="e.g. '2012/12/21', inclusively"
                                   value="{{ GET_data.pub_time_end }}">
                        </div>
                    </div>
                </div>
            </form>
            <div class="archive">
                <h3>Archive</h3>
                <ul class="nav nav-tabs nav-stacked">
                    {% for list1 in archive %}
                        <li>
                            <a class="archive-level1">
                                {{ list1.0.0.date_published|date:"M, Y" }}
                                <strong>({{ list1|sum_month_cnt }})</strong>
                            </a>

                            <div class="row-fluid hide">
                                <div class="day-nav-wrapper span11 offset1">
                                    <ul class="nav nav-tabs nav-stacked">
                                        {% for list2 in list1 %}
                                            <li>
                                                <a class="archive-level2">
                                                    {{ list2.0.date_published|date:"dS" }}
                                                    <strong>({{ list2|length }})</strong>
                                                </a>
                                                <ul class="archive-articles-wrapper hide">
                                                    {% for article in list2 %}
                                                        <li class="archive-article-title">
                                                            <a class="" href={{ article.get_absolute_url }}>
                                                                {{ article.title }}
                                                            </a>
                                                        </li>
                                                    {% endfor %}
                                                </ul>
                                            </li>
                                        {% endfor %}
                                    </ul>
                                </div>
                            </div>
                        </li>
                    {% endfor %}
                </ul>
            </div>
        </div>
    </div>
{% endblock %}

pages/templates/pages/new_article.html
{% extends "base.html" %}
{% load staticfiles %}
{% block head %}
    <link rel="stylesheet" type="text/css" href="{% static "pages/new_article.css" %}">
    <script>
        $(function () {
            $('#id_content').ckeditor()
        })
    </script>
{% endblock %}
{% block title %}Create A New Article{% endblock %}
{% block content %}
    <div class="new-article-content">
        <div class="header-container">
            <h1 class="new-article-main-header">
                Create A New Article
            </h1>
        </div>
        <div class="new-article-form-wrap">
            <form method="POST" action=""> {% csrf_token %}
                <div class="error_msg">
                    {{ form.non_field_errors }}
                </div>
                <div class="fieldWrapper">
                    <label class="new-article-label" for="id_category">Tag(s)</label>

                    <div class="new-article-checkbox">
                        {{ form.tags }}
                    </div>
                </div>
                <div class="fieldWrapper">
                    <label class="new-article-label" for="id_title">Title</label>

                    <div class="new-article-title">
                        {{ form.title }}
                    </div>

                </div>
                <div class="fieldWrapper">
                    <label class="new-article-label" for="id_content">Content</label>

                    <div class="content-tip meta">
                        Tip: try paste formatted content directly!
                    </div>
                    <div class="textarea-div">
                        {{ form.content }}
                    </div>
                </div>
                <p>
                    <input class="button blue-button new-article-submit"
                           id="new-post-sumbit" type="submit" value="submit">
                </p>
            </form>
        </div>
    </div>
{% endblock %}

pages/templates/pages/pages_base.html
{% extends "base.html" %}
{% load staticfiles %}
{% block head %}
    <link rel="stylesheet" type="text/css" href="{% static "pages/pages_base.css" %}">
    {% block pages_head %}
    {% endblock %}
{% endblock %}
{% block content %}
    <div class="container-fluid">
        {% block pages_content %}
        {% endblock %}
    </div>
{% endblock %}