TeenHope/urls.py
from django.conf.urls import patterns, include, url
from django.conf.urls.static import static

from TeenHope import settings

# Uncomment the next two lines to enable the admin:
from django.contrib import admin

admin.autodiscover()

urlpatterns = patterns('',
                       # Examples:
                       # url(r'^$', 'TeenHope.views.home', name='home'),
                       # url(r'^TeenHope/', include('TeenHope.foo.urls')),

                       # Uncomment the admin/doc line below to enable admin documentation:
                       url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

                       # Uncomment the next line to enable the admin:
                       url(r'^admin/', include(admin.site.urls)),

                       url(r'^forum/', include('forum.urls', namespace="forum")),
                       url(r'^accounts/', include('accounts.urls', namespace="accounts")),
                       url(r'^pages/', include('pages.urls', namespace="pages")),
                       url(r'^$', "forum.views.home", name="home"),
                       url(r'^xadmin/', include('xadmin.urls', namespace="xadmin")),
                       url(r'^network/', include('network.urls', namespace="network")),

) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/urls.py
from django.conf.urls import patterns, url
from accounts import views

urlpatterns = patterns('',
                       url(r'^login/$', views.login, name='login'),
                       url(r'^logout/$', views.logout, name='logout'),
                       url(r'^register/$', views.register, name='register'),
                       url(r'^view_profile/(?P<user_id>\d+)/$', views.view_profile, name='view_profile'),
                       url(r'^forget_password$', views.forget_password, name='forget_password'),
)

forum/urls.py
from django.conf.urls import patterns, url
from forum import views

urlpatterns = patterns('',
                       url(r'^category$', views.all_category_index, name='all_category_index'),
                       url(r'^category/all$', views.all_topic_index, name='all_topic_index'),
                       url(r'^category/(?P<label>\w+)/$', views.specific_category_index, name='specific_category_index'),
                       url(r'^topic/(?P<topic_id>\d+)/new_post/$', views.new_post, name="new_post"),
                       url(r'^topic/(?P<topic_id>\d+)/$', views.topic_detail, name='topic_detail'),
                       url(r'^post/(?P<post_id>\d+)/post_reply/$', views.post_reply, name="post_reply"),
)

pages/urls.py
from django.conf.urls import patterns, url
from pages import views

urlpatterns = patterns('',
                       url(r'^$', views.index, name="index"),
                       url(r'^(?P<article_id>\d+)$', views.detail, name="detail"),
                       url(r'^new_comment/(?P<article_id>\d+)/$', views.new_comment, name="new_comment"),
                       )

xadmin/urls.py
from django.conf.urls import patterns, url
from xadmin import views


urlpatterns = patterns('',
                       url(r'^dashboard/$', views.dashboard, name='dashboard'),
                       url(r'^inbox/$', views.inbox, name='inbox'),
                       url(r'^show_msg_in_inbox/(?P<msg_id>\d+)$', views.show_msg_in_inbox, name="show_msg_in_inbox"),
                       # url(r'^send_msg/$', views.send_msg, name="send_msg"),
                       # url(r'^add_connections/$', views.add_connections, name="add_connections"),
                       url(r'^manage_connections/$', views.manage_connections, name="manage_connections"),
                       url(r'^new_topic/$', views.new_topic, name="new_topic"),
                       url(r'^new_article/$', views.new_article, name="new_article"),
                       url(r'^recent_traces/$', views.recent_traces, name="recent_traces"),
                       url(r'^update_profile/$', views.update_profile, name='update_profile'),
                       url(r'^on_checkbox$',views.on_checkbox,name="on_checkbox"),
                       url(r'^ckbox_select_all/(?P<page>\d+)$',views.ckbox_select_all,name="ckbox_select_all"),
                       url(r'^ckbox_unselect_all/(?P<page>\d+)$',views.ckbox_unselect_all,name="ckbox_unselect_all"),
                       url(r'^ckbox_remove$',views.ckbox_remove,name="ckbox_remove"),
                       url(r'^ckbox_mark$',views.ckbox_mark,name="ckbox_mark"),
                       url(r'^ckbox_unmark$',views.ckbox_unmark,name="ckbox_unmark"),
                       url(r'^inbox_search$',views.inbox_search,name="inbox_search"),
                       url(r'^inbox_mark_one$',views.inbox_mark_one,name="inbox_mark_one"),
                       url(r'^inbox_unmark_one$',views.inbox_unmark_one,name="inbox_unmark_one"),
                       url(r'^chpsw_sendmail$',views.chpsw_sendmail,name="chpsw_sendmail"),
                       url(r'^chpsw_ckhash$',views.chpsw_ckhash,name="chpsw_ckhash"),
                       url(r'^chpsw_doupdate$',views.chpsw_doupdate,name="chpsw_doupdate"),
                       url(r'^mancon_remove$',views.mancon_remove,name="mancon_remove"),
                       url(r'^mancon_newgroup$',views.mancon_newgroup,name="mancon_newgroup"),
                       url(r'^mancon_edit_groupname/(?P<group_id>\d+)$',views.mancon_edit_groupname,name="mancon_edit_groupname"),
                       url(r'^mancon_move_selected/(?P<group_id>\d+)$',views.mancon_move_selected,name="mancon_move_selected"),
                       url(r'^mancon_move_single/(?P<group_id>\d+)$',views.mancon_move_single,name="mancon_move_single"),
                       url(r'^mancon_clear_group/(?P<group_id>\d+)$',views.mancon_clear_group,name="mancon_clear_group"),
                       url(r'^mancon_remove_group/(?P<group_id>\d+)$',views.mancon_remove_group,name="mancon_remove_group"),
                       url(r'^activate_ckhash$',views.activate_ckhash,name="activate_ckhash"),
)

pages/models.py
from django.db import models
from django.contrib.auth.models import User
from django.core.urlresolvers import reverse

from TeenHope import settings


class Tag(models.Model):
    author = models.ForeignKey(User)
    title = models.CharField(max_length=settings.TAG_LENGTH_LIMIT)

    def __unicode__(self):
        return self.title

    def count(self):
        return self.article_set.count()


class Article(models.Model):
    author = models.ForeignKey(User)
    date_published = models.DateTimeField(auto_now_add=True)
    title = models.CharField(max_length=settings.ARTICLE_TITLE_LENGTH_LIMIT)
    content = models.TextField(max_length=settings.ARTICLE_LENGTH_LIMIT)
    tags = models.ManyToManyField(Tag)
    abstract = models.CharField(max_length=settings.ABSTRACT_LENGTH_LIMIT)

    def __unicode__(self):
        return "Article: " + self.title

    def get_absolute_url(self):
        return reverse('pages:detail', kwargs={'article_id': self.id})

    def trace_msg(self):
        return "Create article#%d <strong>%s</strong>" % (self.id, self.title)

    def get_subscribe_subject(self):
        return "%s has created a new article" % self.author.get_profile().nickname

    def get_subscribe_content(self):
        return "<a href=%s>Click here to view</a>" % self.get_absolute_url()


class Comment(models.Model):
    author = models.ForeignKey(User)
    article = models.ForeignKey(Article)
    date_published = models.DateTimeField(auto_now_add=True)
    content = models.CharField(max_length=settings.COMMENT_LENGTH_LIMIT)

    def __unicode__(self):
        return "Comment #%d for Article %s" % (self.id, self.article.title)

    def get_absolute_url(self):
        return reverse('pages:detail', kwargs={'article_id': self.article.id})

    def trace_msg(self):
        return "Post a comment(#%d) on article <strong>%s</strong>" % (self.id, self.article.title)

    def get_subscribe_subject(self):
        return "%s has created a new comment" % self.author.get_profile().nickname

    def get_subscribe_content(self):
        return "<a href=%s>Click here to view</a>" % self.get_absolute_url()

templates/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html>
<head>

    <script src="{% static "js/jquery-1.10.2.js" %}"></script>
    <script src="{% static 'js/jquery-ui-1.10.3/ui/jquery-ui.js' %}"></script>
    <script src="{% static 'ckeditor4.2/ckeditor.js' %}"></script>
    <script src="{% static "bootstrap/js/bootstrap.js" %}"></script>
    <script src="{% static 'tag-it/tag-it.js' %}"></script>
    <script src="{% static 'js/jquery.json-2.4.min.js' %}"></script>

    <link rel="stylesheet" type="text/css" href="{% static "bootstrap/css/bootstrap.css" %}">
    <link rel="stylesheet" type="text/css" href="{% static "bootstrap/css/bootstrap-responsive.css" %}">
    <link rel="stylesheet" type="text/css" href="{% static "font/font-awesome/css/font-awesome.css" %}">
    <link rel="stylesheet" type="text/css" href="{% static "js/jquery-ui-1.10.3/themes/base/jquery-ui.css" %}">
    <link rel="stylesheet" type="text/css" href="{% static "tag-it/tagit.css" %}">
    <link rel="stylesheet" type="text/css" href="{% static "css/base.css" %}">

    {% block head %}
    {% endblock %}
    <title>{% block title %}Defalt Title{% endblock %}</title>
    <script>
        function getCookie(name) {
            var cookieValue = null;
            if (document.cookie && document.cookie != '') {
                var cookies = document.cookie.split(';');
                for (var i = 0; i < cookies.length; i++) {
                    var cookie = jQuery.trim(cookies[i]);
                    // Does this cookie string begin with the name we want?
                    if (cookie.substring(0, name.length + 1) == (name + '=')) {
                        cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
                        break;
                    }
                }
            }
            return cookieValue;
        }
        var csrftoken = getCookie('csrftoken');

        function csrfSafeMethod(method) {
            // these HTTP methods do not require CSRF protection
            return (/^(GET|HEAD|OPTIONS|TRACE)$/.test(method));
        }
        $.ajaxSetup({
            crossDomain: false, // obviates need for sameOrigin test
            beforeSend: function (xhr, settings) {
                if (!csrfSafeMethod(settings.type)) {
                    xhr.setRequestHeader("X-CSRFToken", csrftoken);
                }
            }
        });

        var show_message = function (msg, type) {
            $('.messages-list').text("");
            $('<div class=\"alert alert-'+type+'\">').append(
                            $('<button type="button" class="close" data-dismiss="alert">&times;</button>')
                    ).append(msg)
                    .appendTo($('.messages-list'));
        }

        $(function () {
            $('.messages-list').css({'margin-left': -($('.messages-list').width()) / 2});
            $('.messages-list').hide().fadeIn(500);

            $('.errorlist li').prepend('<i class="icon-exclamation"></i> &nbsp;');
            show_message("<strong>Warning!</strong> This site is still under construction. See footer below for more info.",
            "warning");
        });
    </script>

</head>
<body>

<ul class="messages-list">
    {% for message in messages %}
        <div class="alert {% if message.tags %}{{ message.tags }}{% endif %}">
            <button type="button" class="close" data-dismiss="alert">&times;</button>
            {{ message|safe }}
        </div>
    {% endfor %}
</ul>

<div class="navbar transparent navbar-inverse navbar-fixed-top">
    <div class="navbar-inner">
        <div class="container">
            <a class="brand" href="{% url 'home' %}">
                <strong>Cornucopians</strong></a>

            <div class="nav-collapse">
                <ul class="nav">
                    {% url 'home' as home_url %}
                    <li{% if request.path == home_url %}
                        class="active"
                    {% endif %}><a href="{{ home_url }}"><i class="icon-home"></i>
                        Home</a></li>

                    {% url 'forum:all_category_index' as forum_url %}
                    <li{% if request.path == forum_url %}
                        class="active"
                    {% endif %}><a href="{{ forum_url }}"><i class="icon-comments"></i>
                        Forum</a></li>

                    {% url 'pages:index' as pages_url %}
                    <li{% if request.path == pages_url %}
                        class="active"
                    {% endif %}><a href="{{ pages_url }}"><i class="icon-file"></i>
                        Pages</a></li>
                    {% comment %}
                    <li><a href="#about"><i class="icon-money"></i>
                        Donate</a></li>
                    {% endcomment %}
                </ul>
                <div class="pull-right">
                    {% if user.is_authenticated %}
                        <span>
                        <img class="navbar-img" src="{{ user.get_profile.thumbnail.url }}">
                        </span>
                        <a id="profile-link" class="navbar-text"
                           href="{{ user.get_profile.get_absolute_url }}">
                            <strong>{{ user.get_profile.nickname }}</strong>
                        </a>
                        <a class="navbar-user-btn" href="{% url 'xadmin:inbox' %}">
                            {% if user.get_profile.get_unread_message_cnt %}
                                <i class="icon-envelope icon-large"></i>
                                <span class="subscript inbox-subscript">{{ user.get_profile.get_unread_message_cnt }}</span>
                            {% else %}
                                <i class="icon-envelope-alt icon-large"></i>
                            {% endif %}

                        </a>
                        <a class="navbar-user-btn" href="{% url 'xadmin:dashboard' %}"><i class="icon-gears icon-large"></i></a>
                        <a class="navbar-user-btn" href="{% url 'accounts:logout' %}?next={{ request.get_full_path }}">
                            <i class="icon-signout icon-large"></i>
                        </a>

                    {% else %}
                        <div class="btn-group">
                            <a class="btn btn-primary"
                               href="{% url 'accounts:login' %}?next={{ request.get_full_path }}">
                                <i class="icon-user icon-large"></i>
                                Log in</a>
                            <a class="btn btn-primary dropdown-toggle" data-toggle="dropdown">
                                <span class="caret"></span>
                            </a>
                            <ul class="dropdown-menu pull-right">
                                <li><a href="{% url 'accounts:register' %}?next={{ request.get_full_path }}">
                                    Not a member?</a></li>
                                <li><a href="{% url 'accounts:forget_password' %}">Forget password?</a></li>
                            </ul>
                        </div>
                    {% endif %}
                </div>
            </div>
        </div>
    </div>
</div>

{% block content %}
{% endblock %}


<footer style="height: 100%;">
    <div class="container">
        <div class="row">
            <div class="span12">
                <span>cornucopians © 2013</span>
            </div>
            <div class="span12 footer-warning">
                This site currently is for testing only. Please do not leave important
                information here since the database will be cleared totally once officially
                published. If you find some bugs, or suggestions for improvement, please
                kindly send an email to <strong>csimstu@gmail.com</strong> or
                <strong>rapidhere@gmail.com</strong>. Thank you for visiting.<br>
                If you are interested in supporting us or details in development, please visit
                <a href="https://github.com/csimstu/cornucopia">our project at github</a>.
                Contributors are welcome.
            </div>
        </div>
    </div>
</footer>

</body>
</html>

templates/home.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block title %}
    Cornucopians - a universally friendly onilne community
{% endblock %}
{% block head %}
    <link rel="stylesheet" href="{% static 'css/home.css' %}" type="text/css" media="screen"/>

    <script src="{% static 'js/home-slider.js' %}"></script>
{% endblock %}
{% block content %}

    <section id="feature_slider" class="">
        <!--
            Each slide is composed by <img> and .info
            - .info's position is customized with css in index.css
            - each <img> parallax effect is declared by the following params inside its class:

            example: class="asset left-472 sp600 t120 z3"
            left-472 means left: -472px from the center
            sp600 is speed transition
            t120 is top to 120px
            z3 is z-index to 3
            Note: Maintain this order of params

            For the backgrounds, you can combine from the bgs folder :D
        -->
        <article class="slide" id="cornucopians"
                 style="background: url('{% static 'img/backgrounds/heart_tree.jpg' %}') repeat-x top center;">

            <div class="info">
                <h2>Cornucopians</h2>

                <div>Cornucopians offers a cornucopia of things you need to fight with diseases.</div>
            </div>
        </article>
        <article class="slide" id="together"
                 style="background: url('{% static 'img/backgrounds/lego_squad.jpg' %}') repeat-x top center;">
            <div class="info">
                <h2>Together</h2>

                <div>We unite all teenagers suffering from diseases together to form a support community.</div>
            </div>
        </article>
        <article class="slide" id="window"
                 style="background: url('{% static 'img/backgrounds/peek_from_balcony.jpg' %}') repeat-x top center;">

            <div class="info">
                <h2>Window</h2>

                <div>We want you to see that life is beautiful, and full of hopes.</div>
            </div>
        </article>
        <article class="slide" id="journey"
                 style="background: url('{% static 'img/backgrounds/road_ahead.jpg' %}') repeat-x top center;">

            <div class="info">
                <h2>Journey</h2>

                <div>We are here to help you travel further on the road to recovery.</div>
            </div>
        </article>
    </section>

    <div class="intro row-fluid">
        <div class="container">
            <div class="span9">
                <span>Cornucopians is a non-profit community dedicating for
                    helping physically injured teenagers.</span>

                <p>Cornucopians aims to inspire and encourage teenagers with serious diseases to have a more positive
                    attitude towards
                    life and illness by establishing an online community for them and providing related information.
                </p>
            </div>
            <div class="span3 join-now">
                <a href="{% url 'accounts:register' %}"
                   class="btn btn-success btn-block btn-large">Join Us Now</a>
            </div>
        </div>
    </div>


    <div class="main-wrapper container-fluid">
        <div class="row-fluid">
            <div class="span1"></div>
            <div class="span4">
                <div class="quote">
                    <h2 class="short-headline">
                        <span>quote ignite</span>
                    </h2>

                    <div class="content">
                        <i class="icon-quote-left icon-large"></i>
                        {{ quote_content }}
                        <i class="icon-quote-right icon-large"></i>
                    </div>
                    <div class="author pull-right">
                        {{ quote_author }}
                    </div>
                </div>

                <div class="hot-topics">
                    <h2 class="short-headline">
                        <span>hot topics this week</span>
                    </h2>

                    <div class="content">
                        <ul>
                            {% for topic in hot_topics %}
                                <li>
                                    <h3>
                                        <a class="topic-title"
                                           href="{% url 'forum:topic_detail' topic.id %}">
                                            {{ topic.title }}
                                        </a>
                                    </h3>

                                    <div class="meta">
                                            <span>{{ topic.post_set.count }}
                                                post{{ topic.post_set.count|pluralize }}
                                            </span>
                                            <span>
                                                <i class="icon-edit"></i>
                                                Last edited by
                                                <a href="{{ topic.get_last_post.author.get_profile.get_absolute_url }}">
                                                    {{ topic.get_last_post.author.get_profile.nickname }}
                                                </a>
                                            </span>
                                            <span>
                                                <i class="icon-time"></i>
                                                {{ topic.get_last_post.date_published|date:"P M d" }}
                                            </span>
                                            <span>
                                                <i class="icon-tag"></i>
                                                <a href="{{ topic.category.get_absolute_url }}">
                                                    {{ topic.category.title }}
                                                </a>
                                            </span>
                                    </div>
                                </li>
                            {% endfor %}
                        </ul>
                    </div>
                </div>
            </div>

            <div class="span6">
                <div class="features">
                    <h2 class="short-headline">
                        <span>features at cornucopians</span>
                    </h2>

                    <div class="row-fluid">
                        <div class="feature-item span4 forum-intro">
                            <div class="feature-icon">
                                <i class="icon-comments"></i>
                            </div>
                            <h3><a href="{% url 'forum:all_category_index' %}">forum</a></h3>
                        <span>
                            Forum is the friendly place to post questions, raise doubts, or start discussions on
                            any topic you like.
                        </span>
                        </div>
                        <div class="feature-item span4 blog-intro">
                            <div class="feature-icon">
                                <i class="icon-file"></i>
                            </div>
                            <h3><a href="{% url 'pages:index' %}">blog</a></h3>
                        <span>
                            Here is a mini-functional blog system for every member, to share life stories and
                            experiences, or anything you'd like to let others enjoy.
                        </span>
                        </div>
                        <div class="feature-item span4 connect-intro">
                            <div class="feature-icon">
                                <i class="icon-code-fork"></i>
                            </div>

                            <h3><a href="#">connect</a></h3>
                        <span>
                            Connecting with others is the most effective way to fight against solitude.
                            You can invite friends, send messages, and subscribe those people you are interested in
                            in order to get notified whenever updates come out.
                        </span>
                        </div>
                    </div>
                </div>

                <div class="highlight-pages">
                    <h2 class="short-headline">
                        <span>pages of highlight</span>
                    </h2>

                    <div class="content">
                        <ul class="article-list">
                            {% for article in hot_articles %}
                                <li>
                                    <h3>
                                        <a class="article-title"
                                           href="{% url 'pages:detail' article.id %}">
                                            {{ article.title }}
                                        </a>
                                    </h3>

                                    <ul class="meta">
                                        <li>
                                            <i class="icon-edit"></i>
                                            <a href="{{ article.author.get_profile.get_absolute_url }}">
                                                {{ article.author.get_profile.nickname }}
                                            </a>
                                        </li>
                                        <li>
                                            <i class="icon-time"></i>
                                            {{ article.date_published|date:"P, M d" }}
                                        </li>
                                        <li>
                                            <i class="icon-comment"></i>
                                            <a href="{% url 'pages:detail' article.id %}#comment-list">
                                                {{ article.comment_set.count }}
                                                comment{{ article.comment_set.count|pluralize }}
                                            </a>
                                        </li>
                                        <li>
                                            <i class="icon-tags"></i>
                                            {% if article.tags.all %}
                                                {% for tag in article.tags.all %}
                                                    <span class="tag">
                                                        <a href="{{ tag.get_absolute_url }}">
                                                            {{ tag.title }}
                                                        </a>
                                                    </span>
                                                {% endfor %}
                                            {% else %}
                                                <span class="tag">No tag</span>
                                            {% endif %}
                                        </li>
                                    </ul>
                                    <div class="abstract">
                                        {{ article.abstract|safe }}
                                    </div>

                                    <a class="btn btn-primary pull-right" href="{% url 'pages:detail' article.id %}">Read
                                        more</a>
                                </li>

                            {% endfor %}
                        </ul>


                    </div>
                </div>
            </div>
            <div class="span1"></div>
        </div>
    </div>
{% endblock %}